[package]
name = "wasm-codecs-oxipng"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>", "Cyril Wanner <info@cyr.li>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/oxipng.rs"

[dependencies]
oxipng = { version = "3.0.1", default-features = false }
wasm-bindgen = "0.2.70"
log = { version = "0.4", features = ["release_max_level_off"] }

[profile.release]
lto = true
opt-level = "s"
